### ISSUE TITLE
As a user I want a configuration interface so that I can easily select from a range of options that will customise the container stack to my requirements

### ISSUE THREAD

**Issue by transien7** [paradroid001/desertemu#3]
### Description:
Being able to read and write configs will mean we can customise container stacks for the specific work we are doing, whilst keeping as much of the code generic as we can. A UI seems the best option, possibly graphical or even on the console. The config process should be able to present options in some way to the user and allow them to adjust parameters and ultimately write out (serialise) a config file. It should also be able to load in (deserialise) a config file, allowing the user to tweak the parameters and serialise the config back out again.

### Success Criteria:
- Uses console UI or a Graphical UI to configure various options (assume a linux desktop environment)
  - PyQT is an option
  - TKinter is another option
  - There may be others, the ideal case is that they are low footprint and have minimal dependencies/requirements.
- Can present a range of customisation controls:
  - Text field
  - Slider
  - Number field
  - Dropdown list
  - Radio buttons
  - Buttons
- Can read and write a config file:
  - Serialisation: Making a bunch of selections / adjustments to the GUI and 'saving' should generate a config file (format is up to you)
  - Deserialisation: Loading a config file, if it's valid, should reflect the config file contents in the UI.
- Actual content for the UI would be things like:
  - Whether to present containers for build tools, emulation platform, or both
  - What the prefix for naming of those containers might be
  - What architecture / endianness to emulate (probably a dropdown)
  - What kernel to build
  - What libc to use
  - What directory the resulting system files should reside in
Note:
* This feature should be able to handle local and remote files

### Tasks
- [x] #9

**Comment by washyking** [comment]
![Image](https://github.com/user-attachments/assets/6e4a89e8-c497-4ce1-a10d-7b186856a7bd)

Started working on looking into tkinter. Currently have a simple gui with one entry box which writes to txt file. Can recieve uploads from user importing text into entry box. 

Going to add extra fields for other content soon hopefully.

Not working in docker am using it seperate as just testing gui.

**Comment by washyking** [comment]
UPDATE

Finished with the gui tool. Saves output to a json file and can read from said json file.

The fact that I did not make it in docker is coming back to bite me. I am currently trying to work with docker and its hard but should hopefully be done by friday, than will chuck the task in review.

![Image](https://github.com/user-attachments/assets/b514c5b3-7482-4ac8-9767-23fff8b6e303)

**Comment by washyking** [comment]
Finished working with docker finally so thats good. Improvements and feedback much appreciated. @paradroid001 @transien7

**Comment by paradroid001** [comment]
Thanks for this - so there was a bit of a code review which is great. Would love to see a demo of this system and a runthrough of what works and what future plans there are, might be easier to give feedback in a live session.
