### ISSUE TITLE
Investigate running PyQT and Tkinter

### ISSUE THREAD

**Issue by paradroid001** [paradroid001/desertemu#9]

**Comment by paradroid001** [comment]
Yeah its working.


![Image](https://github.com/user-attachments/assets/1ef94691-00ad-4a52-9ade-297731c635df)

**Comment by paradroid001** [comment]
Actually, it's not working. It's broken. @paradroid001 Can you help, I am blocked.

**Comment by thomasgrier** [comment]
Decided to use tkinter due to better GUI

**Comment by paradroid001** [comment]
If that's the case, want to give a quick summary of "why" tkinter's UI is "better" in a few dot points, and then close the ticket?
